[package]
name = "enclave"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
async-trait = "0.1.88"
chrono = "0.4.41"
password-hash = "0.5.0"
rand = "0.8.5"
regex = "1.11"
sha2 = "0.10"
hex = "0.4"

[dev-dependencies]
tokio = { version = "1.46.0", features = ["macros", "rt-multi-thread"] }
